version: "3.8"

services:
  bot:
    container_name: fleamarketbot
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - 8080:80

  database:
    image: postgres
    container_name: fleamarketbot-db
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false